apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "intro.labels" . | nindent 4 }}
  name: {{ include "intro.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage.size }}
  storageClassName: standard
