apiVersion: v1
kind: Service
metadata:
  name: {{ include "intro.fullname" . }}
  {{- with .Values.service.labels }}
  labels:
      {{- toYaml . | nindent 8 }}
      {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "intro.selectorLabels" . | nindent 4 }}
